### ISSUE TITLE
How to send commands through serial?

### ISSUE THREAD

**Issue by imaandrew** [acc-/tplink-archer-c2300#2]
Hi there,
I've connected to my router through serial but i'm not able to type in commands. I tried booting it up while holding reset but I couldn't type any commands. How were you able to send it commands through the serial connection?

Thanks,
Andrew

**Comment by acc-** [comment]
You need to press Enter first to activate the console.
If it doesn't work, you must have connection issue - Computer's TX line not connected properly to router's RX. Assuming you're using 3.3v adapter...  if you use 5v, you might cause some damage.

**Comment by imaandrew** [comment]
Ok thanks

**Comment by imaandrew** [comment]
One last question, are you supposed to build dropbear on the router. When I build it on my computer, I get the error `C compiler cannot create executables` and when I run the compiler from the terminal, i get the error: `cannot execute binary file: Exec format error`

**Comment by acc-** [comment]
Not on router - you can build it using cross-compiling on your pc. But why do you want to compile it, instead of using version compiled by me ?

See https://github.com/acc-/tplink-archer-c2300/tree/master/cross-compiled-files - there you can find both the syntax to compile dropbear, as well as precompiled binary.
