### ISSUE TITLE
how to disable/close ssh access to router

### ISSUE THREAD

**Issue by payonel** [acc-/tplink-archer-c2300#4]
I have this same router and I see that it gets an dhcp ip on the network that responds to port 22. I have tried the root+password as you describe but I fail to get access (even with non-interactive shell attempts such as to run `ls`) 

ultimately, I do not want access to the router like this, I want to disable this access. Is this port open for the tplink tether app? I don't want any of that and I haven't been able to find info about this except for this github

thanks for your help

**Comment by acc-** [comment]
I don't remember the defaults, but according to https://github.com/acc-/tplink-archer-c2300/wiki/Limited-SSH-access-without-serial-port it should be disabled by default, because I was setting RemoteSSH to on. Please check your config (download backup .bin and convert to xml) and write the content of <dropbear> section, should look like on the mentioned wiki page.

Which firmware version are you using?

**Comment by payonel** [comment]
i'll have to investigate this another time - I just want to thank you so much for helping with something you're not even responsible for, on your github repo ... you're amazing :)
